name: Deploy Angular apps to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build App-A
        run: npx ng build app-a --configuration production --base-href /angular-monorepo/app-a/

      - name: Build App-B
        run: npx ng build app-b --configuration production --base-href /angular-monorepo/app-b/

      - name: Prepare deployment folder
        run: |
          mkdir deploy
          cp -r dist/app-a/browser deploy/app-a
          cp -r dist/app-b/browser deploy/app-b
          cp deploy/app-a/index.html deploy/app-a/404.html
          cp deploy/app-b/index.html deploy/app-b/404.html

      - name: Deploy all apps to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx ngh --dir=deploy --branch=gh-pages --message="Deploy all apps"
